"""Disposable teaching fixtures; never accept a server URL or private credential.

Run from the repository root after ``uv sync --frozen``. The application remains
the canonical implementation: this file supplies bounded experiments around it.
"""

import argparse
import asyncio
import contextlib
import importlib.util
import json
import os
import re
import shutil
import sqlite3
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from unittest.mock import patch
from uuid import uuid4

ROOT = Path(__file__).resolve().parents[2]
# Direct script execution otherwise puts book/labs, rather than app, on sys.path.
sys.path.insert(0, str(ROOT))


def run(*args, env=None, **kwargs):
    """Use an argument vector: fixture data never becomes shell code."""
    return subprocess.run(args, cwd=ROOT, env=env, check=True, **kwargs)


def lab_environment(database_url):
    """Override every Settings field, including values in the user's .env."""
    from app.config import Settings

    settings = Settings(
        _env_file=None,
        **{name: field.default for name, field in Settings.model_fields.items()},
    )
    settings.database_url = database_url
    settings.jwt_secret = "synthetic-local-book-key-never-deploy-0000000000000000"
    settings.provider = "mock"
    settings.email_provider = "disabled"
    env = dict(os.environ)
    env.update({name.upper(): str(value) for name, value in settings.model_dump().items()})
    env.pop("TEST_DATABASE_URL", None)
    env.pop("TEST_ALLOW_RESET", None)
    return env


@contextlib.contextmanager
def process_environment(values):
    original = dict(os.environ)
    os.environ.clear()
    os.environ.update(values)
    try:
        yield
    finally:
        os.environ.clear()
        os.environ.update(original)


def migration():
    from alembic import command
    from alembic.config import Config
    from alembic.util.exc import AutogenerateDiffsDetected
    from sqlalchemy import Index

    from app.models import Base

    with tempfile.TemporaryDirectory(prefix="is373-migration-") as directory:
        path = Path(directory)
        shutil.copytree(ROOT / "migrations", path / "migrations")
        # SQLite reflects PostgreSQL Float/DOUBLE definitions differently. This
        # index-only experiment changes its private copy, never the CI contract.
        environment_file = path / "migrations" / "env.py"
        environment_file.write_text(
            environment_file.read_text().replace("compare_type=True", "compare_type=False")
        )
        config = Config(str(ROOT / "alembic.ini"))
        config.set_main_option("script_location", str(path / "migrations"))
        env = lab_environment(f"sqlite+aiosqlite:///{path / 'migration_test.db'}")
        with process_environment(env):
            command.upgrade(config, "head")
            table = Base.metadata.tables["conversations"]
            index = Index("ix_lab_conversations_title", table.c.title)
            try:
                command.revision(
                    config, message="lab additive title index", autogenerate=True, rev_id="lab0003"
                )
                command.upgrade(config, "head")
                command.check(config)
                with sqlite3.connect(path / "migration_test.db") as db:
                    assert (
                        db.execute("SELECT version_num FROM alembic_version").fetchone()[0]
                        == "lab0003"
                    )
                    assert "ix_lab_conversations_title" in {
                        row[1] for row in db.execute("PRAGMA index_list(conversations)")
                    }
                # Fixed fault: metadata and the database disagree in this process.
                table.indexes.remove(index)
                try:
                    command.check(config)
                except AutogenerateDiffsDetected:
                    print("Expected: model/schema drift detected")
                else:
                    raise AssertionError("Drift was not detected")
                table.indexes.add(index)
                command.check(config)
                print("Expected: additive index migrated; index comparison has no drift")
                generated = next((path / "migrations" / "versions").glob("lab0003_*.py"))
                print(generated.read_text())
            finally:
                table.indexes.discard(index)


async def stream():
    import codecs

    import httpx

    from app.config import Settings
    from app.providers import HTTPProvider

    values = {name: field.default for name, field in Settings.model_fields.items()}
    values.update(
        provider="openai",
        openai_api_key="synthetic-never-sent",
        email_provider="disabled",
        app_env="development",
    )
    settings = Settings(_env_file=None, **values)
    complete = (
        'data: {"type":"response.output_text.delta","delta":"hello"}\n\n'
        + 'data: {"type":"response.completed","response":{"usage":{"total_tokens":2}}}\n\n'
    )
    real_client = httpx.AsyncClient

    async def normalized(body):
        with patch(
            "app.providers.httpx.AsyncClient",
            lambda **kw: real_client(
                transport=httpx.MockTransport(lambda request: httpx.Response(200, text=body)), **kw
            ),
        ):
            return [item async for item in HTTPProvider(settings).stream([], 64)]

    assert await normalized(complete) == [{"text": "hello"}, {"tokens": 2}]
    truncated = await normalized(complete.split('data: {"type":"response.completed"')[0])
    assert truncated == [{"text": "hello"}]
    print("Observed gap: premature EOF produces text without a terminal usage event")
    wire = 'event: delta\ndata: {"text":"café"}\n\n'.encode()
    split = wire.index("é".encode()) + 1
    chunks = [wire[:split], wire[split:]]
    try:
        chunks[0].decode("utf-8")
    except UnicodeDecodeError:
        print("Expected: decoding each network chunk independently fails")
    else:
        raise AssertionError("The fixture did not split a multibyte character")
    decoder = codecs.getincrementaldecoder("utf-8")()
    text = "".join(
        decoder.decode(chunk, final=i == len(chunks) - 1) for i, chunk in enumerate(chunks)
    )
    assert "café" in text and text.endswith("\n\n")
    print("Expected: incremental decoder retains the complete Unicode frame")


def coverage():
    import coverage as coverage_tool

    with tempfile.TemporaryDirectory(prefix="is373-coverage-") as directory:
        file = Path(directory) / "policy.py"
        # This mutant is intentionally wrong; it is never installed in app/.
        file.write_text("def allowed(owner, caller):\n    return True\n")
        measured = coverage_tool.Coverage(branch=True, source=[directory], data_file=None)
        measured.start()
        spec = importlib.util.spec_from_file_location("lab_policy", file)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        assert module.allowed("alice", "alice")  # Weak positive-only example.
        measured.stop()
        assert measured.report() == 100
        try:
            assert not module.allowed("alice", "bob")
        except AssertionError:
            print("Expected: 100% measured coverage; negative ownership example rejects mutant")
        else:
            raise AssertionError("Negative assertion failed to detect the mutant")


def promotion():
    digest = "sha256:" + "a" * 64
    accepted = {"commit": "b" * 40, "digest": digest, "schema": "0002", "checks": "passed"}

    def permit(candidate, qa, approval):
        if not approval or qa["checks"] != "passed":
            raise ValueError("Approval and passing QA evidence required")
        if any(candidate[key] != qa[key] for key in ("commit", "digest", "schema")):
            raise ValueError("Candidate differs from accepted QA artifact")
        return dict(candidate)

    assert permit(accepted, accepted, True) == accepted
    for candidate, qa, approval in [
        ({**accepted, "digest": "sha256:" + "c" * 64}, accepted, True),
        (accepted, {**accepted, "checks": "failed"}, True),
        (accepted, accepted, False),
    ]:
        try:
            permit(candidate, qa, approval)
        except ValueError as failure:
            print("Expected rejection:", failure)
        else:
            raise AssertionError("Unsafe proposal was accepted")
    print("Expected: same accepted artifact plus approval passes the local policy model")
    print("This is a decision model, not the implemented production promotion gate.")


def local_docker():
    context = os.environ.get("DOCKER_CONTEXT")
    if context:
        endpoint = run(
            "docker",
            "context",
            "inspect",
            context,
            "--format",
            "{{.Endpoints.docker.Host}}",
            capture_output=True,
            text=True,
        ).stdout.strip()
    else:
        endpoint = (
            os.environ.get("DOCKER_HOST")
            or run(
                "docker",
                "context",
                "inspect",
                "--format",
                "{{.Endpoints.docker.Host}}",
                capture_output=True,
                text=True,
            ).stdout.strip()
        )
    if not endpoint.startswith(("unix://", "npipe://")):
        raise RuntimeError("Use a local Docker socket, not a remote/cloud Docker daemon")
    # Freeze the checked endpoint for later CLI calls, regardless of context.
    os.environ.pop("DOCKER_CONTEXT", None)
    os.environ["DOCKER_HOST"] = endpoint


def image():
    local_docker()
    if run("git", "status", "--porcelain", capture_output=True, text=True).stdout.strip():
        raise RuntimeError(
            "Build from a clean book-edition checkout; inspect/save your lab changes first"
        )
    commit = run("git", "rev-parse", "HEAD", capture_output=True, text=True).stdout.strip()
    tag = "is373-book-lab:" + uuid4().hex
    try:
        run(
            "docker",
            "build",
            "--platform",
            "linux/amd64",
            "--build-arg",
            f"COMMIT_SHA={commit}",
            "-t",
            tag,
            ".",
        )
        data = json.loads(
            run("docker", "image", "inspect", tag, capture_output=True, text=True).stdout
        )[0]
        actual = data["Config"]["Labels"]["org.opencontainers.image.revision"]
        assert actual == commit and data["Config"]["User"] == "10001:10001"
        print("Verified source label:", actual)
        print("Local image content ID:", data["Id"])
        assert actual != "0" * 40
        print("Expected: deliberately mismatched source claim rejected")
        print("Local image ID is not evidence of a published registry manifest digest.")
    finally:
        subprocess.run(["docker", "image", "rm", tag], capture_output=True)


def environments():
    local_docker()
    with tempfile.TemporaryDirectory(prefix="is373-environments-") as directory:
        path = Path(directory)
        compose = path / "compose.yaml"
        shutil.copyfile(ROOT / "deploy" / "compose.preview.yaml", compose)
        records = []
        for stage in ("dev", "qa"):
            variables = {
                "DEPLOY_ENV": stage,
                "APP_HOST": f"{stage}.lab.invalid",
                "BASE_URL": f"https://{stage}.lab.invalid",
                "APP_IMAGE": "ghcr.io/kaw393939/is373-ai-chat@sha256:" + "a" * 64,
                "POSTGRES_PASSWORD": "synthetic-" + stage,
                "JWT_SECRET": "synthetic-" + stage + "-" + "0" * 64,
                "TRAEFIK_NETWORK": "lab_unused_network",
            }
            env_file = path / ".env"
            env_file.write_text("\n".join(f"{key}={value}" for key, value in variables.items()))
            env = lab_environment("sqlite+aiosqlite:///:memory:")
            env.update(variables)
            result = run(
                "docker",
                "compose",
                "--env-file",
                str(env_file),
                "-f",
                str(compose),
                "config",
                "--format",
                "json",
                env=env,
                capture_output=True,
                text=True,
            )
            model = json.loads(result.stdout)
            assert model["services"]["app"]["environment"]["PROVIDER"] == "mock"
            assert model["services"]["app"]["environment"]["EMAIL_PROVIDER"] == "disabled"
            records.append(model["name"])
        assert records == ["is373-ai-chat-dev", "is373-ai-chat-qa"]
        print("Verified rendered projects:", ", ".join(records))
        print("Expected: duplicate project-name proposal rejected by distinct-name invariant")
        assert len(set([records[0], records[0]])) != 2
        print("Only configuration rendered; no network, volume or application was started.")


@contextlib.contextmanager
def postgres():
    """Own a new labeled container; cleanup only its returned immutable ID."""
    local_docker()
    token = uuid4().hex
    image = re.search(r"image:\s*(postgres:\S+)", (ROOT / "compose.yaml").read_text())[1]
    result = run(
        "docker",
        "run",
        "-d",
        "--rm",
        "--label",
        f"is373.book-lab={token}",
        "--memory",
        "256m",
        "--cpus",
        "0.50",
        "--pids-limit",
        "128",
        "-p",
        "127.0.0.1::5432",
        "-e",
        "POSTGRES_USER=lab",
        "-e",
        "POSTGRES_PASSWORD=synthetic-local-lab",
        "-e",
        "POSTGRES_DB=lab_test",
        image,
        capture_output=True,
        text=True,
    )
    container = result.stdout.strip()
    if not re.fullmatch(r"[0-9a-f]{64}", container):
        raise RuntimeError("Docker did not return a container ID")
    try:
        for _ in range(40):
            ready = subprocess.run(
                ["docker", "exec", container, "pg_isready", "-U", "lab", "-d", "lab_test"],
                capture_output=True,
            )
            if ready.returncode == 0:
                break
            time.sleep(0.5)
        else:
            raise RuntimeError("Disposable PostgreSQL did not become ready")
        port = run(
            "docker", "port", container, "5432", capture_output=True, text=True
        ).stdout.strip()
        if not re.fullmatch(r"127\.0\.0\.1:\d+", port):
            raise RuntimeError("Expected a loopback-only port")
        url = f"postgresql+asyncpg://lab:synthetic-local-lab@{port}/lab_test"
        env = lab_environment(url)
        yield container, env
    finally:
        inspected = subprocess.run(
            [
                "docker",
                "inspect",
                "--format",
                '{{index .Config.Labels "is373.book-lab"}}',
                container,
            ],
            capture_output=True,
            text=True,
        )
        if inspected.returncode == 0 and inspected.stdout.strip() == token:
            # -v removes only anonymous volumes belonging to this new container.
            run("docker", "rm", "-f", "-v", container, capture_output=True)


def admission():
    with postgres() as (_, env):
        env["TEST_DATABASE_URL"] = env["DATABASE_URL"]
        env["TEST_ALLOW_RESET"] = "lab_test"
        run(
            sys.executable,
            "-m",
            "pytest",
            "-q",
            "tests/integration/test_chat.py::test_parallel_admission_is_atomic",
            env=env,
        )
        print("Expected: PostgreSQL admission test passed without a skip")


def recovery():
    with postgres() as (container, env):
        run(sys.executable, "-m", "alembic", "upgrade", "head", env=env)
        run(
            sys.executable,
            "-m",
            "app.cli",
            "admin",
            env={**env, "ADMIN_PASSWORD": "synthetic-local-book-password-123"},
        )
        limits = json.loads(
            run("docker", "inspect", container, capture_output=True, text=True).stdout
        )[0]["HostConfig"]
        assert limits["Memory"] == 256 * 1024 * 1024 and limits["PidsLimit"] == 128
        print("Verified limits: memory=256MiB pids=128 cpu=0.50")
        print(
            run(
                "docker",
                "stats",
                "--no-stream",
                "--format",
                "{{.MemUsage}}",
                container,
                capture_output=True,
                text=True,
            ).stdout.strip()
        )
        dump = run(
            "docker",
            "exec",
            container,
            "pg_dump",
            "-U",
            "lab",
            "-Fc",
            "lab_test",
            capture_output=True,
        ).stdout
        run(
            "docker",
            "exec",
            container,
            "psql",
            "-U",
            "lab",
            "-d",
            "lab_test",
            "-c",
            "TRUNCATE users CASCADE",
            capture_output=True,
        )
        run("docker", "exec", container, "createdb", "-U", "lab", "restore_test")
        run(
            "docker",
            "exec",
            "-i",
            container,
            "pg_restore",
            "--exit-on-error",
            "-U",
            "lab",
            "-d",
            "restore_test",
            input=dump,
            capture_output=True,
        )

        def scalar(database, sql):
            return run(
                "docker",
                "exec",
                container,
                "psql",
                "-U",
                "lab",
                "-d",
                database,
                "-Atc",
                sql,
                capture_output=True,
                text=True,
            ).stdout.strip()

        assert scalar("lab_test", "SELECT count(*) FROM users") == "0"
        assert scalar("restore_test", "SELECT count(*) FROM users") == "1"
        schema = scalar("restore_test", "SELECT version_num FROM alembic_version")
        assert schema == "0002"
        print(f"Expected: original users=0; restored users=1; restored schema={schema}")
        print("Local restoration evidence does not prove off-host disaster recovery.")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "experiment",
        choices=[
            "migration",
            "stream",
            "coverage",
            "promotion",
            "admission",
            "recovery",
            "image",
            "environments",
        ],
    )
    args = parser.parse_args()
    os.chdir(ROOT)
    if args.experiment == "stream":
        asyncio.run(stream())
    else:
        globals()[args.experiment]()


if __name__ == "__main__":
    main()
