"""Generate teaching excerpts from real symbols; --check rejects drift."""

import argparse
import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "book/generated/code-tours.md"
TOURS = [
    (
        "JWT validation",
        "app/security.py",
        "decode_token",
        "Decode checks claims and expiry. The route still checks current family/user authority.",
    ),
    (
        "Conversation ownership",
        "app/services.py",
        "owned",
        "The lookup includes both resource ID and owner ID. A valid token alone does not grant ownership.",
    ),
    (
        "Refresh rotation",
        "app/services.py",
        "rotate",
        "Follow the family row lock, used-token detection and replacement commit in time order.",
    ),
    (
        "Streaming persistence",
        "app/services.py",
        "generate",
        "Follow provider events and durable state. EOF without a terminal event remains issue #12, not a demonstrated complete contract.",
    ),
    (
        "Database lifetime",
        "app/db.py",
        "database",
        "The engine/pool belongs to the process; individual sessions belong to a unit of work.",
    ),
]


def render():
    parts = [
        "# Listings from canonical source\n",
        "Generated by `scripts/book_snippets.py`; edit source rather than these listings. "
        "The build checks exact excerpt equality. Software excerpts are MIT licensed. "
        "Line numbers describe this checkout; edition evidence fixes its revision.\n",
    ]
    for title, filename, symbol, explanation in TOURS:
        text = (ROOT / filename).read_text()
        node = next(n for n in ast.parse(text).body if getattr(n, "name", None) == symbol)
        start, end = node.lineno, node.end_lineno
        excerpt = "\n".join(text.splitlines()[start - 1 : end])
        parts.extend(
            [
                f"## {title}\n",
                f"{explanation}\n",
                f"Source: [{filename}::{symbol}, line {start}](../../{filename}#L{start}).\n",
                f"```python\n{excerpt}\n```\n",
            ]
        )
    parts.extend(
        [
            "## Identity and ownership in time\n",
            "![Login and authorized conversation read](../assets/identity-trace.svg)\n",
            "Figure 1. A password proves login eligibility; the short-lived access token "
            "carries claims. Each protected request checks the durable session family "
            "and active user, then checks the conversation owner. The textual order is: "
            "browser → login → password verification → session family → JWT; "
            "browser → bearer request → claim validation → current user/family → "
            "owned conversation lookup → response.\n",
        ]
    )
    return "\n".join(parts)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != expected:
            raise SystemExit("Book excerpts drifted: run uv run python scripts/book_snippets.py")
        print("Canonical excerpts match source.")
    else:
        TARGET.parent.mkdir(parents=True, exist_ok=True)
        TARGET.write_text(expected)


if __name__ == "__main__":
    main()
